### ISSUE TITLE
Experiment on other datasets

### ISSUE THREAD

**Issue by ThyrixYang** [titu1994/Keras-just-another-network-JANET#5]
Hi,
The JANET paper seems interesting, but I found the experiments are weak since 99% on MNIST does not mean anything in deep learning. Having implemented this paper, did you run any benchmark on regular sequence tasks such as in NLP or audio processing?

**Comment by ThyrixYang** [comment]
And if so, how did JANET perform on those tasks compare to plain LSTM?

**Comment by titu1994** [comment]
No, I didn't try it on other tasks. The goal of the experiments directory is to check whether my implemention can acheive similar results as the paper.

**Comment by ThyrixYang** [comment]
I see, thanks for your reply.
